sudo: false
language: php
php:
  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
#  - hhvm
#matrix:
#  allow_failures:
#    - php: 5.6
#    - php: hhvm
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
#    - MAGENTO_VERSION=magento-mirror-1.9.1.1
#    - MAGENTO_VERSION=magento-mirror-1.9.0.1
#    - MAGENTO_VERSION=magento-mirror-1.8.1.0
#    - MAGENTO_VERSION=magento-mirror-1.8.0.0
#    - MAGENTO_VERSION=magento-mirror-1.7.0.2
addons:
    code_climate:
        repo_token: 0c75e59e69f6cadcbc20900c79ed274b70bfa7044b95addb2e29bcf9f5542ebe
script:
  - curl -sSL https://raw.githubusercontent.com/hws47a/MageTestStand/master/setup.sh | bash
after_script:
  - cd `mktemp -d /tmp/codeclimate.XXXXXXXX`
  - mkdir build/ && mkdir build/logs && cp ${TRAVIS_BUILD_DIR}/build/logs/clover.xml build/logs/clover.xml
  - composer require codeclimate/php-test-reporter=0.3.0
  - vendor/bin/test-reporter
